version: '3.8'

services:
  frontend:
    build: ./hybrid-lab
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./metrics-backend
    ports:
      - "8000:8000" # Проверь, какой порт в main.py у бэка (обычно 8000 для FastAPI/Uvicorn)
    restart: always
